apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy-exporter.release_name" . }}
  labels:
    app: haproxy-exporter
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ include "haproxy-exporter.release_name" . }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 9101
  selector:
    app: haproxy-exporter
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ include "haproxy-exporter.release_name" . }}
    heritage: {{ .Release.Service }}
  type: {{ .Values.service.type }}
