apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: teamspeak
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      annotations:
        configs-hash: {{ (toYaml .Values.configs) | adler32sum | quote }}
    {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: teamspeak
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
      - name: teamspeak-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range .Values.voicePorts }}
          - containerPort: {{ .containerPort }}
            protocol: UDP
        {{- end }}
        {{- if .Values.service.tcp.enabled }}
          - containerPort: 30033
            protocol: TCP
          - containerPort: 10011
            protocol: TCP
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
          - name: TS3SERVER_LICENSE
            value: accept
        {{- if .Values.configs.allowlist }}
          - name: TS3SERVER_IP_ALLOWLIST
            value: /allowlist.txt
        {{- end }}
          {{- range .Values.extraEnv }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
        volumeMounts:
          - name: teamspeak-data
            mountPath: /var/ts3server/
        {{- if .Values.configs.allowlist }}
          - name: teamspeak-configs
            mountPath: /allowlist.txt
            subPath: allowlist.txt
        {{- end }}
        {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
        {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      volumes:
        - name: teamspeak-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (.Release.Name) "data") | quote  }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: teamspeak-configs
          configMap:
            name: teamspeak
        {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumes | indent 8 }}
        {{- end }}
