{{- if .Values.pod.enableLivestatusTCP -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-livestatus
  labels:
    app: checkmk
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.livestatusTCP.type }}
  ports:
  - name: checkmk-livestatus
    port: 6557
    targetPort: 6557
    protocol: {{ .Values.service.livestatusTCP.protocol }}
    {{if eq .Values.service.livestatusTCP.type "NodePort"}}
    nodePort: {{ .Values.service.livestatusTCP.nodePort }}
    {{end}}
  selector:
    app: checkmk
    release: {{ .Release.Name }}
{{- end }}